{
    'name': 'Gestión de Presupuesto',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'Modulo para control y gestión de presupuestos por área',
    'description': "Control total de presupuesto con validación, reportes y exportación.",
    'author': 'jmfarias',
    'depends': ['base', 'account', 'purchase','purchase_requisition'],
    'data': [
        'security/ir.model.access.csv',
        'views/area_titulo_views.xml',
        'views/presupuesto_views.xml',
        'views/requisicion_views.xml',
        'views/usuario_views.xml',
        'views/flujo_fondos_views.xml',
        'views/reportes_views.xml',
        'views/reportes_vs_contabilidad.xml',
        'views/dashboard_views.xml',
        'views/pagos_programados_wizard_views.xml',
        'report/presupuesto_report.xml',
        'data/ir_cron_data.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}